# Generated by Django 5.1 on 2024-09-02 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('home_phone', models.CharField(max_length=20)),
                ('work_phone', models.CharField(max_length=20)),
                ('cell_phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('session_number', models.IntegerField()),
                ('players', models.ManyToManyField(to='rosterizer.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_curled', models.IntegerField()),
                ('preferred_position1', models.CharField(max_length=10)),
                ('preferred_position2', models.CharField(max_length=10)),
                ('play_with', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosterizer.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosterizer.session')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField()),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='rosterizer.player')),
                ('second', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to='rosterizer.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosterizer.session')),
                ('skip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skip', to='rosterizer.player')),
                ('vice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice', to='rosterizer.player')),
            ],
        ),
    ]
