# Generated by Django 5.1 on 2024-09-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosterizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='home_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
