# Generated by Django 5.1 on 2024-09-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosterizer', '0002_alter_player_cell_phone_alter_player_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
