# Generated by Django 5.1.6 on 2025-12-10 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosterizer', '0003_alter_player_first_name_alter_player_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('never_together', 'Never Together'), ('must_be_together', 'Must Be Together')], max_length=20)),
                ('weight', models.FloatField(default=1.0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_as_player1', to='rosterizer.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_as_player2', to='rosterizer.player')),
            ],
            options={
                'unique_together': {('rule_type', 'player1', 'player2')},
            },
        ),
    ]
